create table if not exists HITS
(
    ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    APP VARCHAR(50) NOT NULL,
    URI VARCHAR(250) NOT NULL,
    IP VARCHAR(50) NOT NULL,
    TIME_STAMP TIMESTAMP NOT NULL
);