version: '3.1'
services:
  stats-server:
    build: stat
    container_name: stats-service-container
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=qwerty
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stat

  stats-db:
    image: postgres:14-alpine
    volumes:
      - /var/lib/postgresql/data/
    container_name: stats-postgres-container
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stat
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwerty

  ewm-service:
    build: main
    container_name: main-service-container
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwerty
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5431/main

  ewm-db:
    image: postgres:14-alpine
    volumes:
      - /var/lib/postgresql/data/
    container_name: ewm-postgres-container
    ports:
      - "7541:5431"
    environment:
      - POSTGRES_DB=main
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwerty
